### ISSUE TITLE
Draw Issue: Breakout not Displaying Lives 🐞

### ISSUE THREAD

**Issue by Ciaxur** [Chad414/yac8-interpreter#1]
## Breakout not Displaying Entire Lives Graphics
**Summary:**
Some games are unplayable, the issue was pinned down to a Draw Call that did not display all the graphics.

![alt text][yac8-issue]

[yac8-issue]: https://raw.githubusercontent.com/Ciaxur/Dump/d402f4710b347d714faa941b1c191114a4308f3e/images/YAC8-Breakout-Issue.png?token=AEJZJP46R726FBRDCID7PRC6ZFYXM "Breakout Issue"

**Comment by Chad414** [comment]
Fixed as of commit 55c4fcb22c83c7f8e3cc4b9d861eba9f146fda4f. Breakout is now fully functional.
